name: Create File

on: 
  workflow_dispatch:

jobs:
  file:
    runs-on: ubuntu-latest
    steps:
      - name: Make directory
        run: mkdir test
      - name: Write small textfile to test directory
        run: echo "hello world" > test/test.txt
      - name: Show directory contents
        run: ls test
